### ISSUE TITLE
AzCopy and Databricks pages in Storage Generate SAS Token fails

### ISSUE THREAD

**Issue by iroelperez** [ssc-sp/datahub-portal#470] opened 2023-03-07 02:36 UTC
**To Reproduce**
1. Go to any Workspace Storage Explorer
2. Click on **AzCopy** and then click **Generate SAS Token**

**Comment by yjmrobert** [comment] 2023-03-07 14:48
closing this as duplicate of #461 

assigning #461 to you 😄

**Closed by yjmrobert** 2023-03-07 14:48 UTC
