### ISSUE TITLE
Save and Discard buttoms not working in the Metadata tab in the workspace

### ISSUE THREAD

**Issue by gwajnberg** [ssc-sp/datahub-portal#1213] opened 2024-06-27 17:36 UTC
### Bug type

DataHub Portal

### What happened?

I tried to fill all the metadata form for submission, after done still either save or discard buttons appears in here as a Text, which I can only highlight with my mouse pointer. I tried 3 different browsers: Edge, firefox and chrome in my Windows OS.

### Expected behavior

The expected behaviour was to have regular buttons which I could click and save or discard the metadata form.

### Reproduction steps

1. I clicked in the " MEtadata" button in the sidebar in my workspace
2. Filled all the empty spaces in the form.
3. Tried to click the Save button, but it is unclickable.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by Sean-Stilwell** [comment] 2024-06-27 17:52
This is being patched with #1210

**Comment by Sean-Stilwell** [comment] 2024-06-28 12:50
Patch has been merged and the issue is resolved in the poc environment

**Closed by Sean-Stilwell** 2024-06-28 12:50 UTC
Labels: bug
